### Basic Tensor manipulation

In [2]:
import torch

t = torch.tensor([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])

In [3]:
t.shape

torch.Size([2, 2, 2])

In [5]:
t.size()

torch.Size([2, 2, 2])

In [12]:
t[0]

tensor([[1, 2],
        [3, 4]])

In [13]:
t[0][0]

tensor([1, 2])

In [14]:
t[0][0][0]

tensor(1)

In [2]:
torch.flatten(t)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
torch.squeeze(t)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [10]:
torch.squeeze(t, dim=0)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [5]:
torch.flatten(t, start_dim=1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

#### Another exmple

In [15]:
t = torch.tensor([[[1],
                       [3]],
                      [[5],
                       [7]]])

In [16]:
t.shape

torch.Size([2, 2, 1])

In [17]:
t[0][0]

tensor([1])

In [8]:
dict(enumerate(["a", "b", "c"]))

{0: 'a', 1: 'b', 2: 'c'}

In [12]:
int(7/2)

3

In [10]:
7%2


1